- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcommGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcommGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsLaceup # SIS
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesCommand
    # gloves: ClothingHandsGlovesColorBlack # SIS
    outerClothing: ClothingOuterArmorBasic # SIS
    id: CentcomPDA
    ears: ClothingHeadsetCentCom # SIS
    belt: WeaponPistolN1984
    pocket1: BoxFolderCentComClipboardThreePapers
    # pocket2: PenCentcom # SIS

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
