# SPDX-FileCopyrightText: 2022 0x6273 <0x40@keemail.me>
# SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Myra <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2026 Skill Issue Station contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Test Packaging

on:
  push:
    branches: [ master, staging, stable ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      # no docs on which one of these is supposed to work, so
      # why not just do both
      - 'RobustToolbox'
      - 'RobustToolbox/**'
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      - 'RobustToolbox'
      - 'RobustToolbox/**'

# Goob-Start
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# Goob-End

jobs:
  build:
    name: Test Packaging
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4.2.2

      - name: Setup Submodule
        run: |
          git submodule update --init --recursive

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5

      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive

      # ubuntu-latest has .NET 10
      # - name: Setup .NET Core
      #   uses: actions/setup-dotnet@v4.1.0
      #   with:
      #     dotnet-version: 10.0.x

      # SIS-Start
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: '**/*.csproj'
      # SIS-End

      - name: Install dependencies
        run: dotnet restore

      - name: Build Packaging
        run: dotnet build Content.Packaging --configuration Release --no-restore /m

      - name: Package server
        run: dotnet run --project Content.Packaging server --log-build --platform linux-x64 # SIS

      - name: Package client
        run: dotnet run --project Content.Packaging client --log-build --no-wipe-release

      # SIS-Start
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: binlogs
      #     path: release/*.binlog
      #     retention-days: 7
      # SIS-End
